### ISSUE TITLE
Language and Vision Diagnosis table from the paper

### ISSUE THREAD

**Issue by avshalomman** [tianyi-lab/HallusionBench#10]
Hi! Thanks for the great work.
I want to reproduce the right side of table 3 (the three columns:  "Language Hallucination", "Visual Illusion", "Mixed").
I ran your evaluation code but I can't seem to find the place that computes these numbers, and I don't understand how to obtain them from the given numbers.

Thanks a lot!
Avshalom

**Comment by rayguan97** [comment]
We give the example to reproduce gpt4v results [here](https://github.com/tianyi-lab/HallusionBench?tab=readme-ov-file#reproduce-gpt4v-results-on-leaderboard). Similarly, we also provide intermediate steps/results for other methods. Those json files are saved and can be accessed using "**Json**" column the [table](https://github.com/tianyi-lab/HallusionBench?tab=readme-ov-file#metric).

**Comment by avshalomman** [comment]
Thanks! Perhaps I've missed it, but the specific table I'm referring to is the one in the screenshot below.
I'm interested in the breakdown of error type (Language\Visual\Mixed) per model.
Any idea how can I calculate these numbers?

Thanks again!

![Screenshot 2024-01-31 at 19 37 44](https://github.com/tianyi-lab/HallusionBench/assets/12231371/2fe31a20-0b6b-424f-91b7-fa6f65e1497f)

**Comment by avshalomman** [comment]
Thanks! Found it now 😅
