### ISSUE TITLE
How to generate "model_prediction"

### ISSUE THREAD

**Issue by OliverLeeXZ** [tianyi-lab/HallusionBench#11]
Could you please give us an example about how to"Run your model on ./HallusionBench.json and save the ouput file as ./HallusionBench_result.json. You need to add the output of your model in the key 'model_prediction'"

**Comment by OliverLeeXZ** [comment]
Can you give us an example using this benmark to test LLAVA1.5?

**Comment by rayguan97** [comment]
We didn't implement those VLMs in our method. You need to prepare the generated output according to our format to evaluate. 

Each question is saved as a dictionary in the json list. You should save the generate output as the value in the corresponding dictionary with 'model_prediction' as the key.

**Comment by OliverLeeXZ** [comment]
I'm sorry, I don't understand what the model should output or do when 'visual_input' is '0' and 'filename' is 'None'? In these situations, how should 'model_prediction' be set?

**Comment by rayguan97** [comment]
You don't need to change those values. We already set those values. You can load the json file and use those values directly.

You should use your model to take the question and set the generated output using 'model_prediction' as key. The output is just text, the answer to the question like human output. For some questions, there are corresponding images, and some questions do not corresponding have images.
