### ISSUE TITLE
Can't wait for evaluation code and data release!

### ISSUE THREAD

**Issue by LengSicong** [tianyi-lab/HallusionBench#2]
Good work! Can't wait for releasing the code and data so that we can adapt this on our current research work on mitigating hallucinations in VLMs.

**Comment by FuxiaoLiu** [comment]
Thanks for your interests! I just released the data and code. We will continue update it these days. If you find our work interesting, please cite this work and [previous work](https://arxiv.org/abs/2306.14565) on mitigating hallucinations in LVLMs.
