### ISSUE TITLE
Calculating performance through json

### ISSUE THREAD

**Issue by wuzhi19931128** [tianyi-lab/HallusionBench#4]
SORRY，in China, it is impossible to access openai service legally. I noticed that the evaluation results of gpt have been stored in json file. Can you directly evaluate the model performance through this json file? Assume that the answer of the model has been stored in the form of hallucionbench_result_sample.json.

Can you provide a guidance plan?

**Comment by rayguan97** [comment]
It depends on what you are trying to do.

1. If you want to evaluate your own method, you can prepare the model response like hallucionbench_result_sample.json. Then the problem would be that you can't use GPT to evaluate the correctness of the response. In that case, you may share your json file with us and we can put it on the leaderboard.
2. If you only want to know about performance of GPT4V and LLava-1.5, we have obtain their responses and provide human labels, which annotate the correctness of their responses. In this case you would not need openai API. 

You may follow those [steps](https://github.com/tianyi-lab/HallusionBench#reproduce-gpt4v-results-on-leaderboard). Remember to comment out "GPT-check" part (line 156 - line 212, line 90 - 93 and adjust line 232 to remove those variables in file [gpt4v_benchmark.py](https://github.com/tianyi-lab/HallusionBench/blob/main/gpt4v_benchmark.py)) and only leave "Human-check" part to see the performance. 

Let me know if this resolve your issue. For help with the evaluation of your own method (situation 1), you may email us (rayguan[AT]umd.edu and fl3es[AT]umd.edu).

**Comment by rayguan97** [comment]
Please let us know and reopen this issue if you have further questions!
