### ISSUE TITLE
Wrong Accuracy per Question

### ISSUE THREAD

**Issue by zhimin-z** [tianyi-lab/HallusionBench#5]
![image](https://github.com/tianyi-lab/HallusionBench/assets/8592144/c2a3c8b2-b85b-4377-92a3-50f761a32c76)
(79.56+38.37)/2 = 58.965

**Comment by rayguan97** [comment]
The number of questions in the easy and hard sets are different, so the formula you mentioned is not correct. You could reproduce those numbers by running out code and check the logic for those calculations.
