### ISSUE TITLE
LLaVA without images

### ISSUE THREAD

**Issue by AtsuMiyai** [tianyi-lab/HallusionBench#7]
Thanks for the insightful work.
I am curious as to how LLaVA 1.5 infers without images. I don't think the official inference code without images is provided, but do you know the code?

**Comment by rayguan97** [comment]
We leave the visual input blank and sent it to LLaVA 1.5 for questions without the image input.

**Comment by Darren-greenhand** [comment]
Hi，Thanks for the insightful work.
I want to know does 'leave the visual input blank' mean your code like this:
```python
with torch.inference_mode(): 
    output_ids = model.generate(
        input_ids,
        # images=image_tensor.to(dtype=torch.float16, device='cuda', non_blocking=True),
        images=None,
        do_sample=True,
        temperature=0.2,
        max_new_tokens=128, 
        use_cache=True,
        stopping_criteria=[stopping_criteria]
    )
```

or you just input a blank image? If so could you upload the image? thx a lot!
