### ISSUE TITLE
[Results] Sharing HallusionBench results evaluated by VLMEvalKit

### ISSUE THREAD

**Issue by kennymckormick** [tianyi-lab/HallusionBench#8]
Dear authors, 
First, congratulations to your great work, which we think a valuable resource for evaluating the hallucination of VLMs. We have implemented HallusionBench in [VLMEvalKit](https://github.com/open-compass/VLMEvalKit/) and evaluated dozens of models on that benchmark. We would like to share these [results](https://github.com/open-compass/VLMEvalKit/blob/main/results/HallusionBench.md) to you and also invite you to try our VLM evaluation toolkit. It supports dozens of VLMs, benchmarks, and provides extensive evaluation results.

**Comment by rayguan97** [comment]
Thank you for integrating our work into your VLMEvalKit and letting us know! We will play with this toolkit, and keep you posted on any updates of our benchmark!

Best,
Tianrui
